### ISSUE TITLE
Echo Test

### ISSUE THREAD

**Issue by Dukat-Gul** [catid/loraftp#2]
I figured out the echo test problems I was having.

In the example notes at the top of the code it indicates to launch with -1 on the listener and 0 for the sender.

When I did that nothing happened. Reading through the code as the crucial line just before the sending call the following was seen.

if (id >= 2)

So I tried instead of 0 on the sender a value of 2 or higher and funnily enough it started to not only send "pings"
`[12:18:48 +08:00] [I] Sent: Ping SendQueueBytes=232`
But on the receiving rpi major activity and packets received.
`[12:18:48 +08:00] [I] Got bytes: 148 3 0 0 5 6 7 8 9 10 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0`

**Comment by catid** [comment]
Thanks updated the comments
